name: RDP

on:
  workflow_dispatch:

jobs:
  run_rdp:
    runs-on: windows-latest
    
    steps:
      - name: 1. Konfigurasi dan Aktifkan Layanan RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          $username = "rdpuser"
          $password = "GitHubTailscaleRDP!2025" # GANTI PASSWORD INI!
          $SecurePassword = ConvertTo-SecureString -AsPlainText $password -Force 
          New-LocalUser -Name $username -Password $SecurePassword -FullName "Temp RDP User" -Force
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Write-Host "Username: $username"
          Write-Host "Password: $password"
        shell: powershell

      - name: 2. Setup dan Koneksi ke Tailscale
        # Menggunakan Action resmi untuk menyingkat instalasi
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }} 
          tags: tag:github-rdp

      - name: 3. Tampilkan Informasi Koneksi
        run: |
          Write-Host "Koneksi Tailscale sukses. Cek log untuk nama mesin/IP 100.x.x.x"
          C:\Tailscale\tailscale.exe status
        shell: powershell

      - name: 4. Jaga Sesi RDP Tetap Hidup
        run: |
          Write-Host "RDP Aktif. Workflow akan berjalan selama 5 jam 50 menit."
          Start-Sleep -Seconds 21000
        shell: powershell
